Alexander-Miller/treemacs

- treemacs-evil.el
See https://github.com/melpa/melpa/pull/4760
> Fix broken package dependency version in treemacs-evil

- README.org
- treemacs-branch-creation.el
- treemacs-faces.el
Add treemacs-directory-collapsed-face which is used for the directory name of collapsed nodes.
> Add treemacs-directory-collapsed-face

- src/elisp/treemacs-mode.el
See https://github.com/Alexander-Miller/treemacs/issues/204 and the code is from @tarsius https://github.com/tarsius/moody/issues/17
> Add support for moody mode-line

- src/elisp/treemacs-async.el
Don't try to run the git command with non-string paths.
> [Git] Fix git with open dir/project extensions

- README.org
edit [#398](https://github.com/Alexander-Miller/treemacs/pull/398)
> [Docs] Fix README.org typo

- src/scripts/treemacs-git-status.py
This builds on #403.
Currently, `treemacs-git-status.py` concatenates output into a string. This makes Python do a lot of GC freeing the previous string, and spend most of its time in the `brk` syscall reallocating the heap.
This PR makes the script build the output into a list, and only `join` it at the very end.
Before the change building a hash table of 22204 entries took 8 seconds and 20418 `brk`s, after it takes 317 milliseconds and 19 `brk`s. The output was identical in my test case (containing both Git status changes and a recursive scan over an expanded directory).
Very likely fixes #379.
> [Git] Improve Git script performance

- src/scripts/treemacs-git-status.py
https://github.com/Alexander-Miller/treemacs/issues/421
> [Git] Fix gitignored file's directories as modified status.

- src/elisp/treemacs-customization.el
Bug fix: don't fail on (Windows) systems without python installed
> [Compatibility] Improve python3 detection on windows

- README.org
- src/elisp/treemacs-mode.el
- src/elisp/treemacs-mouse-interface.el
- src/extra/treemacs-evil.el
> Drag and drop support using left click(mouse 1)

- README.org
> [Docs] Update projects prefix key bindings

- README.org
- src/elisp/treemacs-customization.el
- src/elisp/treemacs-rendering.el
The ascending/descending orders seemed to be reversed.
> Fix the sorting order

- README.org
- src/elisp/treemacs-customization.el
- src/elisp/treemacs-rendering.el
Hopefully I haven't missed anything.
resolves #584
> [Rendering] Add directory / file name transformers

- src/extra/treemacs-persp.el
Fix https://github.com/Alexander-Miller/treemacs/issues/597
> [Persp] Update persp-mode integration summary

- Cask
- Makefile
- README.org
- src/elisp/treemacs-compatibility.el
- src/elisp/treemacs-interface.el
- src/extra/treemacs-perspective.el
>  Compatibility with perspective.el

- Cask
- Makefile
- src/elisp/treemacs-themes.el
- src/extra/treemacs-all-the-icons.el
Add a new theme using `all-the-icons`
> Add all-the-icons theme

- src/elisp/treemacs-mode.el
The slashes for the tail of Clippy's speech bubble were one on top of
the other, like this:
\\
\\
This is clearly the most important PR you've ever received :P
> [Misc] Align some slashes for Clippy

- README.org
- src/extra/treemacs-tab-bar.el
Adds support for `tab-bar-mode` based on the support for perspectives. From my limited testing so far, it appears to work well and as I'd expect. 
Fixes #901
> Tab bar mode

- src/elisp/treemacs-workspaces.el
Fixes compatibility with emacs trunk, where an additional item was added to the
project-current list.
> [Workspaces] Use project-root function.

- src/elisp/treemacs-core-utils.el
This PR replaces internal calls made directly to both `switch-to-buffer`, `display-buffer-in-side-window`, et al. with the preferred method of window management in *newer* Emacsen.
Instead of setting window dedication, window size, and side bar position directly, the code defers this to `display-buffer` with a suitable `ACTION` strategy.
Now a user can override how Treemacs displays its main window by configuring `display-buffer-alist`:
```elisp
("^ \\*Treemacs" display-buffer-in-side-window
(side . right)
(window-width . 30))
```
Note that although I've tested it, I am not familiar with the complications of the code writ large, so it's possible there are some feature regressions. But it works well, and this is guaranteed to place nice with all and sundry that use `display-buffer-alist`.
> Prefer `display-buffer' to home-grown window management

- Changelog.org
- src/elisp/treemacs-interface.el
- src/elisp/treemacs-mode.el
- src/elisp/treemacs-mouse-interface.el
- src/extra/treemacs-evil.el
See [issue 994](https://github.com/Alexander-Miller/treemacs/issues/994)
> Paste here

- src/elisp/treemacs-mode.el
Fix for missing code after https://github.com/Alexander-Miller/treemacs/pull/1043
> [UI] Fix doom-modeline to use new treemacs-segment

- src/extra/treemacs-icons-dired.el
fixes https://github.com/Alexander-Miller/treemacs/issues/1123
> Dired buffer's modifed flag should not change
