Alexander-Miller/treemacs

- treemacs.el
Currently, treemacs-init doesn't initialize the root correctly in dired-mode buffers because (buffer-file-name (current-buffer)) is always nil for such buffers. Looking at the buffer's default-directory is a more reliable way of getting the root. Also, it avoids the need to check if the buffer-file-name is a file or a directory.
> Use default-directory variable instead of buffer-file-name to pick root

- treemacs.el
Handle case when treemacs is initialized in root directory
> do not remove slash if path only contains slash

- treemacs-visuals.el
I had a problem with the icon of the selected file disappearing.
Before:
After:
> Fix selected-icon-background to work with default Emacs theme

- treemacs-visuals.el
The very common ".cc" wasn't present so I've added the most common C++ extensions to the list.
> Added more C++ extensions

- treemacs-visuals.el
It's better to defadvice around enable/disable theme rather than load theme. After loading a theme, a user may enable or disable it, and treemacs won't match the new colors. On the other hand, load-theme calls enable theme, so it's not necessary to defadvice load-theme.
> Fix incorrect icon background colors after enabling/disabling theme

- README.org
I saw a typo, so I did a quick flyspell check of the whole file.
---
I'll mention the typo on the wiki page here, since wiki pages don't seem to support pull requests.
On the Wiki page: https://github.com/Alexander-Miller/treemacs/wiki
The last word in the first bullet point is missing an `i`:
>If you want to get a feel for the codebase look to the functions treemacs and treemacs--push-button, they're general entry points for a large part of treemacs' functionalty.
before:
`functionalty`
after:
`functionality`
> Fix readme.org typos

- treemacs-compatibility.el
Commit 3984a01c8b54509b6 didn't replace usage of removed variable
`treemacs--buffer-name`in advice to function
`popwin:{create,close}-popup-window` with
`treemacs--get-framelocal-buffer`.
> Fix undefined variable error in popwin advice

- src/elisp/treemacs-tags.el
The `treemacs-icon-tag-leaf-text` now is the unicode black slightly small circle and it's quite rare as a glyph in many fonts. I suggest you switch to using the very similar but far more common unicode bullet instead.
> Use unicode bullet instead of black slightly small circle

- src/elisp/treemacs-tags.el
People set all kinds of mode hooks to the major modes. For modes such as js-mode or python-mode, there are a lot of linters or code analyzers that call out to external processes. The problem currently with treemacs's way to get tags for a file is that it uses a real buffer complete with it's major mode, and as soon as it has gathered all the tags from the imenu index, the buffer is killed immediately, while the launched processes are still running. When the processes return a result, the buffer would have been killed and a `Selecting deleted buffer` error will result, and stops the rest of the get tags business. This PR fixes this bug. This PR also makes getting the tags slightly faster as well.
> Temporarily disable run-mode-hooks during imenu index

- src/elisp/treemacs-projectile.el
Couldn't figure out why the fixes for the toggling issue (https://github.com/Alexander-Miller/treemacs/issues/183) didn't seem to be updated for my installation and then I remembered that I was using `treemacs-projectile` as well, updating it with the same code (apart from adding the `projectile-project-root` prompt) seems to fix it
> moving same treemacs function into treemacs-projectile

- README.org
- src/elisp/treemacs-customization.el
- src/elisp/treemacs-persistence.el
For those of us that'd like to centralize cache files and folders, this change:
1. Renames `treemacs--persist-file` to `treemacs-persist-file` (to imply that it is now public and safe to modify), 
2. Defines it with `defvar` so that, if a value has already been assigned to the variable, it won't be changed. `defconst` disregards customizations and resets its value much like `setq` does. 
3. Removes the hardcoded creation of the `~/.emacs.d/.cache` directory (`(f-mkdir user-emacs-directory ".cache")`.
4. Updates the reference to `treemacs-persist-file` in the README.
This makes it possible to truly customize where treemacs saves its persistence file.
EDIT: Or should I have used `defcustom`?
> Fix hardcoded treemacs--persist-file

- README.org
- src/elisp/treemacs-visuals.el
The icons aren't quite the right size for me.
I mainly work with two environments, in one of them I use a 200 DPI monitor and therefore I need the icons to be double the size to match the size of the text.
The other environment I work with has a 96 DPI monitor but I use a small font, which means I actually need the icons to shrink a little to match the size of the text.
This variable allows me to right-size the icons to accomodate both.
> An option to customize the icon size.

- src/elisp/treemacs-interface.el
IMO, most of the times it's better to have the original name as a default rename target, i.e. you'd like to only change a file extension or fix a tiny typo in a filename :slightly_smiling_face: 
`C-w` should do the trick if you don't like the original name one bit anyways
> Preserve original file name when renaming it

- README.org
This typo doesn't seem covered by #197
> fix typo in README.org

- README.org
problem:
Five internal links lead to 404 pages, for example these two:
```
[[Installation][below]]
[[Custom Icons][highly customizable]]
```
solution:
Use the same internal link names as in the TOC, with the leading pound symbol and the first letter in lowercase:
```
[[#installation][below]]
[[#custom-icons][highly customizable]]
```
Possible cause:
The links probably work fine in Emacs, because the Org manual: https://orgmode.org/manual/Internal-links.html
lists the current links as an option:
>Links such as ‘[[My Target]]’ or ‘[[My Target][Find my target]]’ lead to a text search in the current file.
but github doesn't seem to support text searching in org files, the links are instead translated like this:
https://github.com/Alexander-Miller/treemacs/blob/master/Installation …
> [README.org] Fix five 404 internal links on github

- src/elisp/treemacs-mode.el
Add support for [doom-modeline](https://github.com/seagle0128/doom-modeline)
before
after
> Add support for doom-modeline

- src/elisp/treemacs-extensions.el
- in order macroexpansion to work properly the face should be double quoted.
> [Extensions] Double quote the face

- src/elisp/treemacs-mode.el
- src/extra/treemacs-projectile.el
- This makes it easy to adjust keybindings for commands in one place, even
when they are defined in different source files.
- This change also makes it easier for users to adjust keybindings, as
discussed in bug #337.
- Probably `treemacs-evil.el` could be modified accordingly as well; I have
not investigated this further.
- This patch does not change any keybindings
> [Keybinds] Introduce keymaps for commands that share a common prefix

- src/elisp/treemacs-impl.el
This PR fixes two issues with project extensions:
- `treemacs-find-file-node` fails if it's looking for e.g. `README.md` and a project extension provides a node containing `README.md` before the file node. In that case, the regex search for `README.md` will match the extension node, and `treemacs-find-file-node` continues to treat the path as a string, and of course fails.
- `treemacs-find-node` and `treemacs-goto-node` don't handle project extension nodes at all. This causes an error e.g. when collapsing a project with an expanded project extension and then re-expanding it.
> [Extensions] Fixes to project extensions

- src/elisp/treemacs-workspaces.el
`treemacs--consolidate-projects` compares project paths as strings after finishing edit. If top-level extensions exist, this will fail.
This PR skips `:custom` buttons.
> [Workspaces] Fix workspace editing with top-level extensions

- src/elisp/treemacs-extensions.el
- src/elisp/treemacs-impl.el
- src/elisp/treemacs-rendering.el
- src/elisp/treemacs-workspaces.el
**Problems**
- New projects are not inserted between top-level extensions
- Inserting a project clears the DOM if there are no other projects, but DOM might have extension-related data
- When there are no projects, separators are rendered incorrectly between top-level extensions
- When top-level extensions' predicate says no, whitespace might be rendered incorrectly
- When there are no projects, top-level extensions are not rendered.
**Solution**
Keep a marker for the project add position, at the EOL of the last project. If no projects, at the EOL of the first extension positioned at 'top. When no extension, at BOB and not moving with insertion.
- When adding the first project, don't reset DOM because it might still contain extension-related data.
- Always render the projects, even when …
> [Extensions] Manage projects correctly with extensions

- src/scripts/treemacs-git-status.py
There was an argument missing in `find_recursive_entries`. 
Additionally, if the expanded directory contained a symlink loop, `treemacs-git-status.py` would hang indefinitely. Might <span>fix</span> #379 at least for some cases. This solution loses information about files behind symlinks though.
> [Git] Fix errors in find_recursive_entries

- README.org
- src/elisp/treemacs-async.el
- src/elisp/treemacs-core-utils.el
- src/elisp/treemacs-customization.el
- src/elisp/treemacs-extensions.el
- src/elisp/treemacs-faces.el
- src/elisp/treemacs-filewatch-mode.el
- src/elisp/treemacs-follow-mode.el
- src/elisp/treemacs-macros.el
- src/elisp/treemacs-mode.el
- src/elisp/treemacs-persistence.el
- src/elisp/treemacs-rendering.el
- src/elisp/treemacs-workspaces.el
- src/scripts/treemacs-dirs-to-collapse.py
- test/test-treemacs.el
- test/treemacs-test.el
Currently, if a previously persisted project does not exist, Treemacs will remove it without prompting, and this change will be persisted when quitting Emacs. This becomes a problem when you happen to start Emacs without your network mounts and the only option for recovery is to `kill -9` Emacs.
This PR adds a new setting `treemacs-missing-project-action` with options `ask`, `remove`, and `keep`. Ask is the default, since deleting user's configuration without prompting is not very nice, and `keep` might leave users thinking that Treemacs is broken because a project suddenly refuses open.
Treemacs seems to handle missing directories pretty well, so I didn't add any state about existence to the project nodes.
The `ask` option will give an abort/retry/fail -style prompt, with options to …
> [Persistence] Handling of missing persisted projects

- src/elisp/treemacs-macros.el
Turns out that I broke Emacs 25. Emacs 25 does not have gensym by default, use make-symbol.
> [Compatibilty] Fix Emacs 25

- src/elisp/treemacs-core-utils.el
Top-level paths start with `(:custom Root-Key)`, i.e. the root path already contains two parts. Stop iterating earlier to account for that. Before, attempting to find a top-level extension's node that was not directly visible did not work. Also, finding the top-level extension root failed.
> [Extensions] Fix `treemacs--find-custom-top-level-node`

- src/elisp/treemacs-core-utils.el
Non-existent string paths should return nil rather than executing default case of finding a custom project node.
Can be tested with `(treemacs-goto-node "something-that-does-not-exists")` and the same for `treemacs-find-node`. Previouly this raised an error.
> [Core] Fix treemacs-goto-node and treemacs-find-node

- src/elisp/treemacs-core-utils.el
Make `treemacs-current-button` simpler and faster by using `text-property-not-all`.
> [Core] Simplify treemacs-current-button

- src/elisp/treemacs-async.el
- src/scripts/treemacs-git-status.py
Set GIT_OPTIONAL_LOCKS=0 in environment. Don't use --no-optional-locks, since it is only available in Git 2.14. This prevents errors with simultaneous git commands running alongside git status.
> [Git] Don't lock Git index when updating status

- src/elisp/treemacs-visuals.el
This fixes extensions using `treemacs-pulse-on-*` on a button with a non-image icon.
> [Visuals] Don't trigger treemacs--pulse-png-advice on non-image icons

- src/elisp/treemacs-core-utils.el
`treemacs--find-custom-top-level-node` must go to the node even if it is in DOM.
Otherwise, if a child node of a top-level extension is updated, `treemacs-do-update-node` tries to update the top-level node with the update tab action of its child.
> [Core] Fix updating of custom root-level nodes

- src/elisp/treemacs-customization.el
Previous code fails with:
version-to-list: Invalid version syntax: ‘'c:\Program' is not recognized as an internal or external command,
operable program or batch file.’ (must start with a number)
if the Python binary is in a path with a space, e.g. "c:\Program Files\...".
Quote the path with `shell-quote-argument` to fix this.
> Quote paths to commands that may contain spaces

- src/elisp/treemacs-async.el
- src/elisp/treemacs.el
* If pfuture-stderr is fbound, use it and show stderr to the user.
* If pfuture-result does not parse as a hash table, show a message to the user rather than causing an error.
With the current master of pfuture this discards git script output if it does not parse as a hash table.
With [this version](https://github.com/Alexander-Miller/pfuture/pull/5), it keeps working even when Git prints warnings to stderr. stderr is logged with messages.
> [Git] Fix handling of Git script warnings v2

- src/elisp/treemacs-core-utils.el
- src/elisp/treemacs-macros.el
- src/elisp/treemacs-rendering.el
- test/test-treemacs.el
* `treemacs-update-node` now work with file nodes
* `treemacs-update-node` ignores hidden nodes, setting their `treemacs-dom-node->refresh-flag` instead.
* **Semantic change: `treemacs-update-node` silently ignores non-existent nodes. This is because extensions cannot know what extension nodes have been displayed. E.g. Treemacs Bookmark has to update all ancestors of a bookmarked path, even when the directory is not open in Treemacs.**
* `treemacs-is-path-visible?` fixed to check that all DOM ancestors are expanded instead of only checking that the node is in DOM.
* `treemacs-is-path-visible?` works with all kinds of nodes.
* **Semantic change: return type of `treemacs-is-node-visible?`  is now boolean, since collapsed non-variadic top-level nodes don't exist in DOM.**
* …
> [Core][Extensions] Fixes to update node

- src/elisp/treemacs-async.el
Connected to the issue https://github.com/Alexander-Miller/treemacs/issues/453
I noticed that I have this issue only inside virtualenvironments created with `virtualenvwrapper`, this fixes the issue.
> [FIX] remove `-S` flag from python status call

- src/elisp/treemacs-core-utils.el
This bug occurs when read-directory-name opens a GUI dialog box and
asks for a directory. This way the selected directory doesn't end with
a trailing '/'. This commit fixes that.
Reproduction steps:
1. Open Right Click menu
2. Click on *Move*
This will bring up the GUI dialog box. Choose a destination directory
and confirm. This will throw an error without this commit.
> Add trailing '/' so that `f-move` doesn't throw any error

- README.org
- src/elisp/treemacs-async.el
problem:
(executable-find "python3") doesn't work in windows, because the executable is
called python.exe, and it's located in a python37 directory.
solution:
use (treemacs--find-python3) which has windows support
> [Core] Use find python 3 command with windows support

- src/elisp/treemacs-extensions.el
This fixes errors with `:icon-closed-form` for extensions.
> [Extensions] Fix :icon-closed-form for extensions

- src/elisp/treemacs-compatibility.el
As https://github.com/deb0ch/emacs-winum/pull/22 was merged, we can switch to regex now
> [Compatibility] switch to regexes in winum ignore

- src/scripts/treemacs-single-file-git-status.py
[Git] Addresses issue: https://github.com/Alexander-Miller/treemacs/issues/550
Deadlock can happen when large amounts of data are returned from
git commands inside Popen() with stdout=PIPE.
Relevant reference can be found here:
https://docs.python.org/3/library/subprocess.html#subprocess.Popen.wait
Adjusting to ensure that treemacs can handle larger projects that trigger this condition by avoiding the deadlock condition all together.
> [Git] Fix deadlock in git status python subprocesses

- src/scripts/treemacs-single-file-git-status.py
Addresses issue #540 
PEP 498: Formatted string literals were not available until
Python3.6.  Adjusted `treemacs-single-file-git-status.py`
to use generally available interpolation formatting.
> [Git] Fix syntax error for Python3.* < Python3.6

- src/elisp/treemacs-filewatch-mode.el
I found some strange renamed events, such as `old-name` is "recentf" and `new-name` is "recentf~".
https://github.com/Alexander-Miller/treemacs/blob/d653a14ae8aea89d166edb825580fde31c8328f1/src/elisp/treemacs-filewatch-mode.el#L178-L185
This will cause ignored file to be displayed.
> [Rendering] Fix create ingnored file.

- src/elisp/treemacs-scope.el
- it breaks extensions (e. g. lsp-treemacs)
> [Misc] Verify that shelf is not nil before using it

- README.org
- src/elisp/treemacs-customization.el
- src/elisp/treemacs-mode.el
Allows user to specify their `treemacs` mode-line format through setting variable `treemacs--user-mode-line-format` to desired value without overriding `treemacs--setup-mode-line` function.
> Add support for custom mode line format

- README.org
Second take of the PR with commit under ```[Docs]```.
> Fix minor typo in user mode line format variable

- src/elisp/treemacs-icons.el
[leex](https://hexdocs.pm/phoenix_live_view/Phoenix.LiveView.Engine.html) (Live EEx) is used as a template for Elixir Phoenix LiveView.  
So using the elx-light icon is appropriate.
> [Icons] Use elx-light for leex (PhoenixLiveView Template).

- src/elisp/treemacs-mode.el
Make sure buffer-local `header-line-format` is set to `nil` when
`treemacs-user-header-line-format` is set to `nil`. This change is
useful for those who use a header line instead of a mode line. When no
custom header is set for treemacs, it now does not show the global
one.
Before the change:
After the change:
> [Header Line] Hide global header line if there is one

- README.org
- src/elisp/treemacs-icons.el
Starting in Emacs 27, Emacs has native image transform functions that work without imagemagick support compiled in.  If those transforms are available, use them instead of just checking for imagemagick.
> [Icon resize] Use native image tranforms if available

- src/elisp/treemacs-customization.el
- src/elisp/treemacs-fringe-indicator.el
- Fix display property of the fringe overlay 
This worked because the defcustom and the bitmap were on the same
symbol.
The fringe property is expecting the symbol of the bitmap, so this
ignored the value of the defcustom.
- Make the default fringe bitmap bigger and fix type of the defcustom
The default bitmap didn't fill the whole line in my config
> Fix fringe customization

- Makefile
-L . is required to find the test files.
Fixes jorgenschaefer/emacs-buttercup#198
> Fix for  jorgenschaefer/emacs-buttercup#198

- README.org
treemacs-perspective was spelt wrong so when I copied the spelling from the
README file and pasted it into my configuration to install, I got an error
stating that no package exists in Melpa by that name. I corrected this just
in-case someone else does the same thing in the future, then there won't be any
errors.
> fix: treemacs-perspective misspelling as treemacs-persective

- src/elisp/treemacs-customization.el
The latest Emacs 28 requires this.
> Add version to `define-obsolete-variable-alias' invocation

- src/elisp/treemacs-filewatch-mode.el
- src/elisp/treemacs-rendering.el
- src/extra/treemacs-magit.el
`treemacs-magit--schedule-refresh` calls `treemacs--set-refresh-flags` with
`magit-refresh`, which, being a change event not explicitly handled, causes the
above warning. The only side effect of the call to `treemacs--set-refresh-flag`
is to cause the `treemacs` project to be refreshed, though, so call
`treemacs-project->refresh` directly, fixing the message.
----
#
> Fix unknown change event: `magit-refresh`

- src/elisp/treemacs-bookmarks.el
- src/elisp/treemacs-mouse-interface.el
- src/elisp/treemacs-tags.el
- src/extra/treemacs-perspective.el
Here from https://github.com/nex3/perspective-el/issues/144
The treemacs-perspective wrapper calls `persp-killed-hook` incorrectly. This hook in Perspective does not have a "scope" or "name" parameter. The perspective being killed is the current perspective, and the usual introspection helpers for determining the current perspective are available.
Thanks to @Randy1Burrell for reporting the bug and testing the patch.
> Fix Perspective compatibility

- README.org
In the `use-package` documentation it suggested that when using the `:after`
keyword with multiple packages, they should be in a list. This have become
apparent to me after working with `treemacs` for sometime and getting certain
errors. I updated the example in the doc, just in-case other users copy the
examples and try to use it directly without modification, then it will just work
without problems.
If applied, this commit will:
- Update the example that uses use-package :after key word with multiple
packages to be a list.
> [Doc] Update examples to adhere to use-package semantics

- src/elisp/treemacs-persistence.el
I found one bug. If I use multibyte symbols in workspace name or path it renders like that
The reason of such behavior in using `insert-file-contents-literally` which doesn't decodes text from file.
> Fix reading treemacs-persist-file containing multibyte symbols

- src/elisp/treemacs-compatibility.el
When 6c431174dd9 introduced treemacs--file-name-handler-alist, it
mistakenly used the wrong format for alists. This broke TRAMP
integration, because the `file-name-handler-alist` was no longer a valid
alist. Fortunately, this is a trivial fix.
> Fix treemacs--file-name-handler-alist for TRAMP

- src/extra/treemacs-all-the-icons.el
`.gitattributes` file should also share the same icon as `.gitignore` in `all-the-icons` integration.
> [Icon] .gitattributes file should share the same icon with .gitignore

- Extensions.org
Looks like when calling the query-function of an expandable node, the "btn" binding no longer works, but "node" does
> Fix sample extensions code

- src/elisp/treemacs-bookmarks.el
On startup `bookmark-alist` is always empty, unless it's populated somewhere else, hence, calling `treemacs-bookmark` results in "Didn't find any bookmarks" error, even if bookmarks do exist. Made this quick fix that populates `bookmark-alist` inside `treemacs-bookmark` call, if needed
> Populate bookmark-alist from default file

- src/elisp/treemacs-async.el
- src/elisp/treemacs-bookmarks.el
- src/elisp/treemacs-compatibility.el
- src/elisp/treemacs-core-utils.el
- src/elisp/treemacs-customization.el
- src/elisp/treemacs-diagnostics.el
- src/elisp/treemacs-dom.el
- src/elisp/treemacs-extensions.el
- src/elisp/treemacs-faces.el
- src/elisp/treemacs-filewatch-mode.el
- src/elisp/treemacs-follow-mode.el
- src/elisp/treemacs-fringe-indicator.el
- src/elisp/treemacs-header-line.el
- src/elisp/treemacs-hydras.el
- src/elisp/treemacs-icons.el
- src/elisp/treemacs-interface.el
- src/elisp/treemacs-logging.el
- src/elisp/treemacs-macros.el
- src/elisp/treemacs-mode.el
- src/elisp/treemacs-mouse-interface.el
- src/elisp/treemacs-persistence.el
- src/elisp/treemacs-rendering.el
- src/elisp/treemacs-scope.el
- src/elisp/treemacs-tag-follow-mode.el
- src/elisp/treemacs-tags.el
- src/elisp/treemacs-themes.el
- src/elisp/treemacs-visuals.el
- src/elisp/treemacs-workspaces.el
- src/elisp/treemacs.el
- Only section headings should begin with three or more semicolons.
Regular comments as well as all non-heading text in the library
headers should begin with only two semicolons.
- Once the extra semicolon is removed, it looks quite ugly that there
is no empty line between the Commentary heading and its body, so add
that line.
- Use `fill-paragraph` on text in the library commentaries.
> Make library commentaries comply more with the conventions.

- src/elisp/treemacs-icons.el
I have almost as many `foo.org_archive` files as `foo.org` files.
It's configurable but since `.org_archive` is the default I guess
it's ok to have it in there.
I also removed the duplicate elisp icon entry in a different
commit (in case you don't want to add org_archive by default).
Thanks,
Daniel
> Add org_archive as extension for org files

- src/elisp/treemacs-customization.el
Fixes #844.
Paths to Cygwin binaries utilizing magic cookie symlinks may cause
problems when they show up as a result of running the "where" command.
Keep searching the remaining paths returned from the "where" command
when unexpected errors occur while attempting to obtain the version
from the python binary.
> [Core] Search for python on Windows even with unexpected errors.

- src/elisp/treemacs-icons.el
- src/extra/treemacs-all-the-icons.el
[heex](https://hexdocs.pm/phoenix_live_view/assigns-eex.html#:~:text=.heex%20extension%20(HTML%20EEx)) (HTML EEx) is used as a template for Elixir Phoenix.
> [Icons] Use elx-light for heex (HTML EEx).

- src/elisp/treemacs-icons.el
eln is the new Emacs native compilation extension
edn files contain Clojure syntax
> Assign icons for edn and eln files

- src/extra/treemacs-all-the-icons.el
Support for .gradle files was added to all-the-icons in this MR:
https://github.com/domtronn/all-the-icons.el/pull/311
> Removing custom Gradle icon

- src/elisp/treemacs-async.el
- src/elisp/treemacs-customization.el
- src/scripts/treemacs-git-status.py
- src/scripts/treemacs-single-file-git-status.py
The default `--ignored[=traditional]` seems to recursively visit all
files within a project even if `--untracked-files=all` is not
supplied. This may take a lot of time for project with a very large
tree where the root node is ignored.
See #921 for a more thorough explanation.
> Use `--ignored=matching` with `git status`

- README.org
Hi!
I feel like the original wording is not too clear about the fact that the projects would be actually wiped from the workspace file. I had thought that the command would just temporarily focus on a single project.
> clarify side effects of treemacs-display-current-project-exclusively

- README.org
Noticed this on a fresh install of treemacs
Causes `Error (use-package): treemacs/:config: Wrong type argument: symbolp, 'treemacs-hide-dot-git-directory`
> Fix README Typo

- src/elisp/treemacs-annotations.el
- src/elisp/treemacs-core-utils.el
- src/elisp/treemacs-fringe-indicator.el
- src/elisp/treemacs-interface.el
- src/elisp/treemacs-rendering.el
- src/elisp/treemacs-visuals.el
- src/elisp/treemacs-workspaces.el
- src/extra/treemacs-icons-dired.el
To reproduce, have emacs built with native compilation and notice the compilation logs. You can then open the offending file and run `M-x emacs-lisp-native-compile-and-load` before and after the changes to see the warning is removed.
```
Warning: ‘point-at-bol’ is an obsolete function (as of 29.1); use ‘line-beginning-position’ or ‘pos-bol’ instead.
Warning: ‘point-at-eol’ is an obsolete function (as of 29.1); use ‘line-end-position’ or ‘pos-eol’ instead.
```
Note: there is another warning:
```
Error: Eager macro-expansion failure: (error "‘buffer-local-value’ is an obsolete generalized variable.")
```
But I do not know how to tackle this one :cry: .
> Fix emacs native compilation warnings

- src/elisp/treemacs-interface.el
There're an error message when try `treemacs-copy-relative-path-at-point` with emacs29, 
> Wrong type argument: stringp, nil
The reason is the `kill-new` function will return the string result in emacs28, but it return nil in emacs29.
And the manual for `kill-new` didn't promise to return the target string.
This PR will fix the error message in emacs29.
Please help review the change. Thanks.
> [Interface] fix copy-functions used `kill-new` not work in emacs-29

- src/scripts/treemacs-single-file-git-status.py
Thanks for a nice package!
I'm stuck on a system with Python 3.6 and got the problem described in #956.
The issue is that [io.BufferedReader.read1](https://docs.python.org/3.6/library/io.html#io.BufferedReader) needs an argument in Python 3.6, and `-1` is not supported. But if I understand the code correctly, it should be enough to read one byte, so I made it so locally and it seems to work fine for me. Perhaps the fix could be acceptable for treemacs master as well?
> Support Python 3.6 in treemacs-single-file-git-status.py

- src/elisp/treemacs-interface.el
- Changed to (ace-window)
When you have multiple emacs frames, and have
```
(setq treemacs-default-visit-action 'treemacs-visit-node-ace)
```
It wouldn't raise the other frame through X.
> Fix visit-node-ace not focusing when there are multiple emacs frames.

- src/elisp/treemacs-workspaces.el
- src/extra/treemacs-magit.el
- src/extra/treemacs-mu4e.el
- src/extra/treemacs-persp.el
- src/extra/treemacs-perspective.el
- src/extra/treemacs-projectile.el
- src/extra/treemacs-tab-bar.el
My attempt to fix [issue 1002](https://github.com/Alexander-Miller/treemacs/issues/1002). I added logic to programmatically rename a treemacs workspace and then added hooks for persp-mode and perspective.el.
I also did some spelling fixes in other files. All the spelling fixes are in a separate commit for logical clarity.
- I've only tested the `treemacs-perspective--on-perspective-rename` function manually since I don't use `perspective.el`.
- There are more places where the rename function could be inserted to be used, but I left them alone for the time being as I don't know the treemacs codebase that well.
- Along with the previous point, I don't know if the rename function was written as efficiently as possible, so let me know if there are obvious improvements to be made.
Apologies …
> [Persp] Rename treemacs workspace when persp is renamed

- src/elisp/treemacs-mode.el
Using the extra segment, the current workspace name will be shown on the doom-modeline. I have provided a screenshot to show how it looks. I have chosen for the minor-mode-face to make a difference between the major-mode (Treemacs) and the workspace name.
> [UI] Add current workspace name to doom-modeline

- src/elisp/treemacs-mode.el
Revert until #1049 has a working solution that also works with native compilation
> [UI] Revert changes to show current workspace name for doom-modeline

- src/elisp/treemacs-mode.el
> Show workspace name in doom-modeline

- src/elisp/treemacs-interface.el
Hi and thanks for the great package!
Currently `treemacs-delete-other-windows` calls `treemacs--select-not-visible-window`, with the assumption that the treemacs window is not visible anymore. The assumption can be false since `delete-window` doesn't delete treemacs in all setups (e.g. when `treemacs-display-in-side-window` is `t` and treemacs is in a side window). The result is that calling `treemacs-delete-other-windows` on the treemacs window splits the treemacs side window vertically. This PR fixes that.
> Fix treemacs-delete-other-windows

- src/elisp/treemacs-treelib.el
The same as was done for extensions in 0a3d2bd67cfb56468fbeea1e0be86436c049e931
> [Treelib] Let extensions control help-echo

- src/elisp/treemacs-icons.el
Why?:
- ClojureDart is a new and coming dialect of Clojure. Thus its files should have the same icon as other Clojure files.
This change addresses the need by:
- Add "cljd" as additional Clojure file extension
> add: Icon for ClojureDart filetype

- src/extra/treemacs-tab-bar.el
If a tab's selected buffer is the Treemacs buffer when switching away from a tab and back to that tab, the Treemacs buffer will temporarily not be considered part in the current tab. My original technique for getting the current tab was either always wrong or based on the best we could do at the time with the APIs available. This method of getting the current tab seems to work consistently.
> [Tab Bar] Correct method for getting current tab

- src/elisp/treemacs-async.el
The change is introduced in commit ac3f0706bf6248b7321da683438efdcc6bce3e4c.
> [Git] Unquote `treemacs-git-executable` variable

- src/elisp/treemacs-core-utils.el
`treemacs--std-ignore-file-predicate` has a long list of checks to determine whether a file should be ignored. One of them is to see whether it ends in `~`, i.e., it's a backup file.
Emacs allows people to customize backup file names, and `treemacs--std-ignore-file-predicate`'s test fails when someone uses a nonstandard extension like `.bak` for backup files. Thankfully, Emacs includes the `backup-file-name-p` function to test whether something is a backup filename. It's a simple matter of replacing `(eq ?~ last)` with `(backup-file-name-p ,file)`.
> Ignoring nonstandard backup files
